### ISSUE TITLE
编译SDL出错

### ISSUE THREAD

**Issue by TaoheGit** [APCVSRepo/hmi_sdl_android#1]
Hi AP Team
使用NDK编译sdl_core的时候出现如下错误：
mi_sdl_android/sdl_core/src/thirdPartyLibs/jsoncpp/src/lib_json/json_value.cpp:484:39: error: 'OutputDebugString' was not declared in this scope
     OutputDebugString(L"delete map_\n");

OutputDebugString应为Windows平台函数，cmake已设置SYSTEM_NAME=Android，json_value.cpp这个代码是不是有问题？

**Comment by TaoheGit** [comment]
Hi
我在编译的时候发现有许多未定义的错误
'XXXX' was not declared in this scope
现在github上面的代码是不是在NDK下编译有些问题？

**Comment by BrandonHe** [comment]
@TaoheGit 
我们正在解决这些问题。
现在github上是我们更新后的代码，所以可能按以前的编译步骤会出问题。最后的编译参考步骤还是以wiki为主。

**Comment by BrandonHe** [comment]
@TaoheGit 
Hi Tao,
该问题已解决，验证通过。请拉取最新的代码。

谢谢！
Brandon
