### ISSUE TITLE
编译中出现的问题反馈

### ISSUE THREAD

**Issue by TaoheGit** [APCVSRepo/hmi_sdl_android#3]
Hi AP Term：
我在编译sdl_core的时候出现几个小问题，跟你们反馈一下。
1.在目录sdl_core目录下的CMakeLists.txt文件中的
message(STATUS "Current CMAKE_BUIDL_TYPE is ${CMAKE_BUIDL_TYPE}")为笔误，应改为
message(STATUS "Current CMAKE_BUILD_TYPE is ${CMAKE_BUILD_TYPE}")
2.通过make-standalone-toolchain.sh生成toolchain工具时，应在CMakeLists.txt中设置相应的头文件路径和动静态库的路径。
3.在用第二部生成的toolchain工具编译sdl_core时，会出现如下错误：
error: 'pthread_condattr_init' was not declared in this scope
error: 'pthread_condattr_destroy' was not declared in this scope
经过检查发现在生成的android-xx-toolchain/sysroot/usr/include/pthread.h中，并没有定义上述函数。而在相应的文件android-ndk-r10e/platforms/android-xx/arch-arm/usr/include/pthread.h文件中却定义了上述函数。
这个问题的出现，是不是说明make-standalone-toolchain.sh的使用有些问题？
4.将CMakeLists.txt文件的头文件路径和动静态库的路径设置到android-ndk-r10e/platforms/android-xx/arch-arm/usr/include/和android-ndk-r10e/platforms/android-xx/arch-arm/usr/lib，编译可正常通过。运行时有没有问题我暂时还没有验证。

**Comment by BrandonHe** [comment]
Hi Tao,
1. resolved, 
2. Yes, we have, please see [here](https://github.com/APCVSRepo/hmi_sdl_android/blob/master/sdl_core/CMakeLists.txt#L44)
3, You need add both ndk toolchian and android ndk version package location to system PATH,

具体编译:
- 可以参考[wik](https://github.com/APCVSRepo/hmi_sdl_android/wiki/SDL-Android-Environment-Configuration-and-Build)帮助
- 这里我是新搭的64位Ubuntun14,04 环境,编译通过
- 3.6版本是暂时的，我们正在移植到sdl_core 4.0.0版
