### ISSUE TITLE
hmi_sdk编译说明

### ISSUE THREAD

**Issue by TaoheGit** [APCVSRepo/hmi_sdl_android#5]
hmi_sdk的代码和doc目录下的编译说明不一致，有没有最新代码的编译说明？

**Comment by BrandonHe** [comment]
@TaoheGit 我们还在更新，方便给我更多你的联系信息吗？除了github，也可以邮件联系

**Comment by TaoheGit** [comment]
好的 我的邮箱: taohe_2016@foxmail.com
另外我想加入你们的项目

**Comment by BrandonHe** [comment]
@TaoheGit 
Feel free to contribute to our project, this is open source. But before pull request you need to test your codes and have a local verification.

**Comment by BrandonHe** [comment]
Have updated help files.
