### ISSUE TITLE
android平台移植问题请教

### ISSUE THREAD

**Issue by qmu1986** [APCVSRepo/hmi_sdl_android#7]
你好：
我们现在想把SDL往android平台的车机上移植，我已经按照你的方法编译出了libsmartdevicelink.so,然后注意到包里面有一个QtApp-release-signed.apk，所以我将这个apl安装到andorid的车机上，显示的界面如附件所示
![Uploading 微信图片_20170624120118.jpg…]()

，点击按钮没什么作用，我知道网易云音乐是支持SDL的，所以我将车接接上了一个装有网易云音乐的手机，但是也没有任何反应。
想请教下：
    1.这个apk如何使用？
    2.有没有其他的往android平台移植的相关版本和资料？
谢谢！

**Comment by BrandonHe** [comment]
@qmu1986 
由于之前已经邮件回复你们了，所以关闭该issue。

**Comment by kishankanhaiya** [comment]
Hi @qmu1986 
we are also facing the same issue??
Did u get the solution??,if so please let me know??
