### ISSUE TITLE
SDL运行时出现signal 11错误

### ISSUE THREAD

**Issue by ilikegithubcom** [APCVSRepo/hmi_sdl_android#8]
操作系统版本：android4.4.2
原因：初步怀疑与路径和权限有关
建议解决方法：smartDeviceLink.ini文件，设置EnablePolicy = false

**Comment by BrandonHe** [comment]
@ilikegithubcom 
谢谢你的问题和建议。

**Comment by Gnagdhar** [comment]
@ilikegithubcom
Please can you tell that your application is running as expected?? r u able to connect device??
