### ISSUE TITLE
porting sdl for android

### ISSUE THREAD

**Issue by kishankanhaiya** [APCVSRepo/hmi_sdl_android#9]
![screenshot from 2017-07-24 15 15 09](https://user-images.githubusercontent.com/19657849/28517695-e856dd02-7082-11e7-9080-a3a0732f85da.png)
This is the error I am getting error while porting sdl for android. This is the error while building the AppLinkHMI.pro in QT.

**Comment by BrandonHe** [comment]
@kishankanhaiya
These are link errors, if you were not change the .pro file, please check the library was built for Aandroid_armv7 not X86.

**Comment by fanqiang001** [comment]
These are link errors, these indicate that the Linux library is linked,not Android,please make sure the project configuration is Android.

**Comment by kishankanhaiya** [comment]
@BrandonHe 
Hello sir,
Actually above problem is resolved.
But when i build the AppLinkHMI.pro file in Qt creator am not able to build .apk file.(I think this may be because am using (Qt 5.2.1 in PATH (qt5)/usr/lib/x86_64-linux-gnu/qt5/bin/qmake) as Qt version.

One More thing the .apk file that was already build in repo for which architecture.

Warm Regards
Kishan

**Comment by BrandonHe** [comment]
@kishankanhaiya 
It do have influence for your build, please choose the right **Kits**, **Qt Version**, **Compiler** and **Debuggers** in configuration **Option** _Build & Run_

The .apk file that was already build is **Android for armeabi-v7a(GCC 4.9, Qt5.5.1)**

**Comment by kishankanhaiya** [comment]
@BrandonHe 
I am using apk file in android with RPI 3 board with android Naugets but app is not responding.

Warm Regards
Kishan

**Comment by BrandonHe** [comment]
@kishankanhaiya 
Android Naugets is 7.0, there has android version update changes. We suggest you build your own apk file with sdl core newest version 4.3.1.

This is not code issue, so I closed this.

**Comment by kishankanhaiya** [comment]
@BrandonHe 
Hello Thanks for your response.
I want to know that the flow of sdl_core, which is the main function which is going to be called when I create Library file(libSmartDeviceLink.so)(or when we did ./SmartDeviceLink in Linux).
If i get to know about this function ,then i can  easily port it to Android using Android studio.


Warm Regards 
Kishan

**Comment by BrandonHe** [comment]
@kishankanhaiya The architecture of SDL core, you can reference [smartdevicelink.com](https://www.smartdevicelink.com/en/guides/core/software-architecture-document/table-of-contents/),
